[package]
name = "embassy-crypto"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Global cryptography backend with software fallback"
repository = "https://github.com/embassy-rs/embassy"
keywords = ["embedded", "crypto", "unitrait"]
categories = ["embedded", "no-std", "cryptography"]
rust-version = "1.80"

[dependencies]
embassy-crypto-driver = { path = "../embassy-crypto-driver" }
sha1 = { version = "0.10", default-features = false, optional = true }
sha2 = { version = "0.10", default-features = false, optional = true }
md-5 = { version = "0.10", default-features = false, optional = true }
hmac = { version = "0.12", default-features = false, optional = true }
digest = { version = "0.10", default-features = false, optional = true }

[features]
default = []
software-hmac = []
software-hash = ["dep:sha1", "dep:sha2", "dep:md-5", "dep:hmac", "dep:digest"]
