[package]
name = "embassy_crypto"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Global cryptography backend with software fallback"
repository = "https://github.com/embassy-rs/embassy"
keywords = ["embedded", "crypto", "unitrait"]
categories = ["embedded", "no-std", "cryptography"]
rust-version = "1.80"

[dependencies]
embassy_crypto_driver = { path = "../embassy_crypto_driver" }

[features]
default = []
software-hmac = []
